### ISSUE TITLE
Ajustes gerais

### ISSUE THREAD

**Issue by DanielPortods** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#53]
## Descrição
issue direcionada para separar e definir os ajustes que serão feitos até a entrega final.

### Rich Picture: Emily
- [x] Especificar a plataforma utilizada (LucidChart);
- [x] Descrever a metodologia de desenvolvimento.

### Personas:
- [x] Desenvolver um background para as personas;

### Questionário:
- [ ] Desenvolver uma introdução;
- [ ] Descrever a metodologia de desenvolvimento (Como foi feito, quantidade de resposatas, perguntas obrigatórias, tempo, plataforma, etc...);
- [ ] Colocar descrição antes das seções;
- [ ] Desenvolver uma conclusaão a partir da análise dos dados levantados.

### Introspecção:
- [x] Desenvolver uma introdução;
- [x] Descrever a metodologia de desenvolvimento (Como foi feito, quem participou, etc...);

### Brainstoming: Sergio
- [x] Formatar a planilha utilizada;
- [x] Disponibilizar a planilha em modo de visualização.

### Todos os requisitos:
- [ ] Desenvolver uma introdução;
- [ ] especificar os requisitos que não estão no APP;

### First Things First: Emily
- [x] Detalhar mais a metodologia de desenvolvimento (Como foi feito, quem participou, etc...);
- [x] Disponibilizar a planilha em modo de visualização.

### MoSCoW:
- [ ] Descrever a metodologia de desenvolvimento (Como foi feito, quem participou, etc...);

### Casos de Uso:
- [x] Aumentar qualidade imagem;
- [x] Colocar legenda da imagem;

## Critérios de Aceitação
- [ ] Tarefas realizadas e publicadas.

**Comment by sergiosacj** [comment]
Novas melhorias e correções:

## Introdução:
- [ ] colocar referencia do chung

## Backlog:
- [ ] link clicável para a tabela do excel

## História de usuários:
- [ ] Mudar formatação para facilitar leitura
